
//책 검색
###
GET  http://localhost:4001/books/search?query=9791194383437&mode=isbn&pageNo=1

//책 1개 상세검색
//9788409783076
//9791141602451
###
GET  http://localhost:4001/books/search/9791127468509

//배포판
###
GET  http://api.nearbybook.kr/books/search/9791141602451


###
GET  http://localhost:4001/books/trending



###
GET  http://localhost:4001/books/naver/9788409783076


###

GET http://data4library.kr/api/libSrch